FROM tecnativa/docker-socket-proxy@sha256:1f5038b54f06c3e18422902cf00ba21803d1c97805aae032e5e6673d532d3459

ARG TRAEFIK_MANAGER_BUILD_DATE=unknown

RUN : "${TRAEFIK_MANAGER_BUILD_DATE}" && apk upgrade --no-cache
